### ISSUE TITLE
💗 this repo!!

### ISSUE THREAD

**Issue by PySimpleGUI** [Sven-Bo/one-line-gui#1]
One of **_the_** most "fun" things that I've done using PySimpleGUI are the 1-liners.  They've been crazy to discover over the life of the project.  

It would be awesome if you had a simple table in your readme with each row being the line of code and the window it makes.  Or any screenshots would do as I think visitors would love to see what you're making.

You inspired me to try making a new one.  Never done one like this before.
| Code | Widow |
| -- | -- | 
| ```python final_dir = [key for key, value in sg.Window('Choose Direction', [[sg.Text('Choose a direction you want to go')], [[sg.Radio(direction, group_id=1, k=direction, enable_events=True)]for direction in ('North', 'South', 'East', 'West')]], disable_close=True).read(close=True)[1].items() if value is True][0] ``` |  ![image](https://user-images.githubusercontent.com/46163555/162958155-47b96162-8aee-431e-a50a-a395dbba9332.png) |

In a way they're parlor tricks, but they also demonstrate the power of using the Python language as a meta-language for PySimpleGUI.  Being able to use list comprehensions to create layouts was the thing that convinced me that maybe I had made something of value to others.

Thanks for making this repo!  It has been a wonderful way to start my day!  ![image](https://user-images.githubusercontent.com/46163555/162958923-fec2e1d6-6fc1-4704-82c0-0f4996d5b3d4.png)

PySimpleGUI users never fail to impress me with their clever creations.

**Comment by Sven-Bo** [comment]
Fantastic idea, Mike! I have updated the readme [commit: [884c3dc](https://github.com/Sven-Bo/one-line-gui/commit/884c3dcb651a8806d44847a76949067e4cfecfdb)].

The 1-liners are so helpful & easy to use. I am sure I will use them a lot in my upcoming projects. 🚀

**Thank you very much** for all the effort in creating & maintaining PySimpleGUI, Mike!
